version: "2"

services:

  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRESS_PASSWORD: "le-painting1234"
    networks:
      - cybernet
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    image: audy/le-painting
    networks:
      - cybernet
    ports:
      - "4567:4567"
    environment:
      DATABASE_URL: "postgres://postgres:le-painting1234@db:5432/lepainting"
      RACK_ENV: "production"
    depends_on:
      - db

volumes:
  postgres-data:

networks:
  cybernet:
